#pragma once

#include "Debug.h"  // Memory leak detection enabled. Add this header file for each cpp file.

#include "Bluetooth.h"
#include "BufferLock.h"
#include "Camera.h"
#include "Chm.h"
#include "Com.h"
#include "Console.h"
#include "D3DDevice.h"
#include "Device.h"
#include "File.h"
#include "FileExtFilter.h"
#include "FolderMonitor.h"
#include "IStorage.h"
#include "Log.h"
#include "MediaFoundation.h"
#include "MobileBroadband.h"
#include "Monitor.h"
#include "NetworkAdapter.h"
#include "Path.h"
#include "PortableDevice.h"
#include "Power.h"
#include "Preview.h"
#include "Proxy.h"
#include "String.h"
#include "System.h"
#include "Thread.h"
#include "ThreadGroup.h"
#include "Variant.h"
#include "WindowsUtil.h"
#include "Wlan.h"
#include "Wmi.h"